# Generated by Django 5.0.6 on 2024-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0025_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
