# Generated by Django 5.0.6 on 2024-07-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0026_alter_paymentmodel_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinPackageModel',
            new_name='CallPackageModel',
        ),
    ]
