# Generated by Django 5.0.6 on 2024-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0027_rename_coinpackagemodel_callpackagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.FloatField(),
        ),
    ]
