# Generated by Django 5.0.6 on 2024-07-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0029_alter_customermodel_adhaar_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
