# Generated by Django 5.0.6 on 2024-08-01 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0031_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='AdminApp.customermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AdminApp.customermodel')),
            ],
        ),
    ]
