# Generated by Django 5.0.6 on 2024-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0032_ratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='c',
            field=models.BooleanField(default=False),
        ),
    ]
