# Generated by Django 5.0.6 on 2024-08-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0034_rename_c_customermodel_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='customer_password',
            field=models.CharField(default=models.CharField(max_length=50), max_length=100),
        ),
    ]
