# Generated by Django 5.0.6 on 2024-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0035_customermodel_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_password',
            field=models.CharField(default='Name@123', max_length=100),
        ),
    ]
