# Generated by Django 5.0.6 on 2024-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0036_alter_customermodel_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_password',
            field=models.CharField(max_length=100),
        ),
    ]
