# Generated by Django 5.0.6 on 2024-08-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0038_userpurchasemodel_purchase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
    ]
