# Generated by Django 5.0.6 on 2024-09-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0039_customermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_password',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
